name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    env:
      PACKAGE_NAME: docker_launch
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Lint with Flake8
        run: poetry run flake8 tests ${PACKAGE_NAME}

      - name: Format with Black
        if: ${{ matrix.python-version }} != 3.6
        run: poetry run black --check tests ${PACKAGE_NAME}

      - name: Test with pytest
        run: poetry run pytest -n auto -v tests ${PACKAGE_NAME}
